Repository hwgilbert16/scholarsome, pull requests merged in 2023-07, with the labels that each got.

#21 Using heredoc RUN command in Dockerfile
  Dockerfile
Labels: enhancement

#36 Add enhanced documentation/handbook
  .env.compose.example
  .env.dev.example
  .env.docker.example
  apps/api/src/app/app.module.ts
  apps/docs/docs/about.md
  apps/docs/docs/development/_category_.json
  apps/docs/docs/development/development-guide.md
  apps/docs/docs/get-started/_category_.json
  apps/docs/docs/installation/_category_.json
  apps/docs/docs/installation/installing.md
  apps/docs/docs/installation/prerequisites.md
  apps/docs/docs/intro.md
  apps/docs/docs/usage/_category_.json
  apps/docs/docs/usage/creating-sets.md
  apps/docs/docs/usage/flashcards.md
  apps/docs/docs/usage/overview.md
  apps/docs/docs/usage/quizzes.md
  apps/docs/docusaurus.config.js
  apps/front/proxy.conf.json
  apps/front/src/app/header/header.component.html
  apps/front/src/app/study-set/study-set-flashcards/study-set-flashcards.component.ts
  apps/front/src/app/study-set/study-set-quiz/study-set-quiz-question/study-set-quiz-question.component.html
  apps/front/src/app/study-set/study-set-quiz/study-set-quiz.component.html
  package-lock.json
  package.json
Labels: documentation

#35 1. Worked on Feature #32
  apps/api/src/app/auth/auth.controller.spec.ts
  apps/api/src/app/auth/auth.controller.ts
  apps/api/src/app/auth/auth.service.spec.ts
  apps/api/src/app/auth/auth.service.ts
  apps/front/src/app/app.component.html
  apps/front/src/app/auth/auth.service.ts
  apps/front/src/app/header/header.component.html
  apps/front/src/app/header/header.component.ts
  apps/front/src/app/header/header.module.ts
  apps/front/src/app/header/login-modal/login-modal.component.html
  apps/front/src/app/header/login-modal/login-modal.component.ts
  apps/front/src/app/header/register-modal/register-modal.component.html
  apps/front/src/app/header/register-modal/register-modal.component.ts
  apps/front/src/app/header/resend-email/resend-email.component.html
  apps/front/src/app/header/resend-email/resend-email.component.scss
  apps/front/src/app/header/resend-email/resend-email.component.ts
  apps/front/src/app/homepage/homepage.component.html
  apps/front/src/app/homepage/private-guard.service.ts
  libs/shared/src/lib/types/ui/ApiResponseOptions.ts
Labels: work in progress
